Project Initialized
cerebro-iiitv/android-2018 pull request #2
Opened 2018-02-24 12:41 UTC by hshah11

2018-02-24 12:42 UTC, yashLadha commented
@hshah11 There is already a PR for the Initialisation, merging this will lead to conflicts. @Monal5031 Views?

2018-02-24 12:49 UTC, Monal5031 commented
@yashLadha sir I think this one should be merged, since this PR has more file changes compared to previous ones. We can simply copy-paste the changes you made in #1 .

Please use issues next time :sweat:

2018-02-24 12:55 UTC, yashLadha commented
As you like :+1:

2018-02-24 12:58 UTC, Monal5031 commented
btw @yashLadha sir there is no gitignore here, maybe there are something which we shouldn't push. Idk much about android can you please tell if there are such files which we don't need to push?

2018-02-24 12:59 UTC, Monal5031 requested changes

2018-02-24 12:59 UTC, Monal5031 commented on app/.gitignore
> +/build
this should be `build/` I can see the build files are pushed.

2018-02-24 12:59 UTC, yashLadha commented
@Monal5031 the `.idea/` is not of relevance to the code and its subsequent directories, they should be part of `.gitignore`

2018-02-24 13:19 UTC, Monal5031 commented
@yashLadha sir please review once.

2018-02-25 12:03 UTC, Monal5031 commented
ping @yashLadha @neelanshsahai please review and merge.
Get things going ASAP please.

2018-02-25 14:22 UTC, closed without merging